# Generated by Django 5.2.6 on 2025-10-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationType",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("default_template", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("priority", models.CharField(default="normal", max_length=10)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("vendor", "Vendor"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notifications",
                to="users.notificationtype",
            ),
        ),
    ]
