# Generated by Django 5.2.6 on 2025-10-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_discount_amount_and_more"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
