# Generated by Django 5.2.6 on 2025-10-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_variant",
        ),
    ]
