# Generated by Django 5.2.6 on 2025-10-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_remove_order_discount_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("color", models.CharField(default="#000000", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Order Statuses",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentStatus",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Payment Statuses",
                "ordering": ["order", "code"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order.orderstatus",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="order.orderstatus"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="order.paymentstatus",
            ),
        ),
    ]
